version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    working_dir: /home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=DEFAULT_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=DEFAULT_SECRET 